version: "3"
services:
  app:
    image: artomiris/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    volumes:
      - ".:/app"