services:
  app:
    image: app:local
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: make dev
    volumes:
      - "./app:/app"
  caddy:
    image: caddy:2.6
    restart: always
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app