services:
  devapp:
    extends:
      file: docker-compose.yml
      service: app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: make dev
    volumes:
      - ".:/app"
    depends_on:
      - db
  caddy:
    image: caddy:2.6
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER:  ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5