name: push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker-compose -f docker-compose.yml up --abort-on-container-exit
      - run: docker-compose -f docker-compose.yml build app
      - run: docker-compose -f docker-compose.yml push app